In [8]:
import pandas as pd
import numpy as np
import os

# Load Data

This section handles loading the dataset into a pandas DataFrame. It automatically detects the active environment and loads the data accordingly:
- **Google Colab**: Mounts Google Drive and loads the dataset from the specific Colab path.
- **Local Environment**: Loads the dataset from a relative local path (`dataset/customer_churn_dataset.csv`).

In [9]:
try:
    import google.colab
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

if IN_COLAB:
    from google.colab import drive
    drive.mount("/content/drive")
    file_path = '/content/drive/MyDrive/MSC/ML/Dataset/customer_churn_dataset.csv'
    print("Running in Colab: Using Google Drive path.")
else:
    file_path = 'dataset/customer_churn_dataset.csv'
    print("Running Locally: Using local relative path.")
    
if os.path.exists(file_path):
    df = pd.read_csv(file_path)
    print("✅ Successfully loaded the dataset!")
    display(df.head())
else:
    print(f"❌ Error: Could not find the dataset at: {file_path}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Running in Colab: Using Google Drive path.
✅ Successfully loaded the dataset!

,customer_id,tenure,monthly_charges,total_charges,contract,payment_method,internet_service,tech_support,online_security,support_calls,churn
0,1,52,54.20,2818.40,Month-to-month,Credit,DSL,No,Yes,1,No
1,2,15,35.28,529.20,Month-to-month,Debit,DSL,No,No,2,No
2,3,72,78.24,5633.28,Month-to-month,Debit,DSL,No,No,0,No
3,4,61,80.24,4894.64,One year,Cash,Fiber,Yes,Yes,0,No
4,5,21,39.38,826.98,Month-to-month,UPI,Fiber,No,No,4,Yes

In [10]:
print('Data shape:', df.shape)
df.head(5)

Data shape: (20000, 11)

,customer_id,tenure,monthly_charges,total_charges,contract,payment_method,internet_service,tech_support,online_security,support_calls,churn
0,1,52,54.20,2818.40,Month-to-month,Credit,DSL,No,Yes,1,No
1,2,15,35.28,529.20,Month-to-month,Debit,DSL,No,No,2,No
2,3,72,78.24,5633.28,Month-to-month,Debit,DSL,No,No,0,No
3,4,61,80.24,4894.64,One year,Cash,Fiber,Yes,Yes,0,No
4,5,21,39.38,826.98,Month-to-month,UPI,Fiber,No,No,4,Yes

# Clean Data

In [15]:
print("Info of the data: ")
df.info()

Info of the data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       20000 non-null  int64
 1   tenure            20000 non-null  int64
 2   monthly_charges   20000 non-null  float64
 3   total_charges     20000 non-null  float64
 4   contract          20000 non-null  object
 5   payment_method    20000 non-null  object
 6   internet_service  17987 non-null  object
 7   tech_support      20000 non-null  object
 8   online_security   20000 non-null  object
 9   support_calls     20000 non-null  int64
 10  churn             20000 non-null  object
dtypes: float64(2), int64(3), object(6)
memory usage: 1.7+ MB

In [16]:
missing_values = df.isnull().sum()
print('Missing values in each column:')
print(missing_values)

Missing values in each column:
customer_id            0
tenure                 0
monthly_charges        0
total_charges          0
contract               0
payment_method         0
internet_service    2013
tech_support           0
online_security        0
support_calls          0
churn                  0
dtype: int64

+ Check a missing calues with a values with a colcum `internet_service` it missing so i fill the with the `None`

In [20]:
df["internet_service"] = df["internet_service"].fillna("None")

In [22]:
missing_values = df.isnull().sum()
print(missing_values)

customer_id         0
tenure              0
monthly_charges     0
total_charges       0
contract            0
payment_method      0
internet_service    0
tech_support        0
online_security     0
support_calls       0
churn               0
dtype: int64